name: Coverage

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write
  id-token: write
  attestations: write
  issues: read
  discussions: write

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: llvm-tools

      - name: Load cached target directory
        uses: Swatinem/rust-cache@v2
        with:
          key: coverage
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install cargo-hack
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: Generate code coverage
        run: cargo hack llvm-cov nextest --all-features --profile ci --cobertura --output-path coverage.cobertura.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.cobertura.xml
          flags: tests
          name: codecov-umbrella
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Step summary
        run: |
          echo "✅ Code coverage report generated" >> "$GITHUB_STEP_SUMMARY"
