name: Format

on:
  workflow_call:

permissions:
  contents: write

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt

      - name: Load cached target directory
        uses: Swatinem/rust-cache@v2
        with:
          key: fmt
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Check formatting
        run: cargo fmt --check

      - name: Step summary
        run: |
          echo "✅ Format check completed" >> $GITHUB_STEP_SUMMARY
