name: Setup Rust
description: Install Rust toolchain with components

inputs:
  toolchain:
    description: Rust toolchain version
    required: true
  components:
    description: Comma-separated list of components
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Install Rust ${{ inputs.toolchain }}
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}
