[package]
name = "yew-nav-link-demo"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
yew = { version = "0.23", features = ["csr"] }
yew-router = "0.20"
yew-nav-link = { path = "../" }
wasm-bindgen = "0.2"
gloo-timers = { version = "0.4", features = ["futures"] }
web-sys = "0.3"
