# SPDX-FileCopyrightText: 2025 RAprogramm <andrey.rozanov.vl@gmail.com>
#
# SPDX-License-Identifier: MIT

codecov:
  branch: main
  strict_yaml_branch: main
  max_report_age: 12h
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: 90..100

  status:
    project:
      default:
        target: 95%
        threshold: 1%
        base: auto
        if_ci_failed: error
        only_pulls: false
        if_no_uploads: error
        if_not_found: success

    patch:
      default:
        target: 95%
        threshold: 1%
        base: auto
        if_ci_failed: error
        only_pulls: true
        if_no_uploads: error
        if_not_found: success

    changes:
      default:
        base: auto
        if_ci_failed: error
        if_no_uploads: error
        if_not_found: success

  ignore:
    - "tests/**/*"
    - "benches/**/*"
    - "examples/**/*"
    - "**/tests.rs"
    - "**/test_*.rs"
    - "**/*_test.rs"
    - ".github/**/*"
    - "target/**/*"

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes
  show_carryforward_flags: true
  hide_project_coverage: false

github_checks:
  annotations: true

ignore:
  - "*.md"
  - "LICENSE*"
  - ".gitignore"
  - ".rustfmt.toml"
  - "Makefile.toml"
