architect:
  - RAprogramm

docker:
  image: rust:1.91

merge:
  script: |
    echo "CI passed, merging"

release:
  pre: false
  commanders:
    - RAprogramm
  script: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    source $HOME/.cargo/env
    rustup toolchain install nightly
    rustup component add rustfmt --toolchain nightly
    sed -i "s/^version = .*/version = \"${tag}\"/" Cargo.toml
    cargo +nightly fmt --all
    cargo check --all-features
    git commit -am "Release ${tag}"
