architect:
  - RAprogramm

docker:
  image: rust:1.91

merge:
  script: |
    echo "CI passed, merging"

release:
  pre: false
  commanders:
    - RAprogramm
  script: |
    rustup toolchain install nightly
    rustup component add rustfmt --toolchain nightly
    sed -i "s/^version = .*/version = \"${tag}\"/" Cargo.toml
    cargo +nightly fmt --all
    cargo check --all-features
    git commit -am "Release ${tag}"
