# Do not add trailing comma when single element
trailing_comma = "Never"

# Braces stay on the same line
brace_style = "SameLineWhere"

# Align struct fields if below threshold
struct_field_align_threshold = 20

# Wrap and format comments in documentation
wrap_comments = true
format_code_in_doc_comments = true

# Do not collapse struct literals to single line
struct_lit_single_line = false

max_width = 99

# Import grouping
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true

# Enable unstable features (nightly only)
unstable_features = true