name: Read MSRV
description: Read rust-version from Cargo.toml

outputs:
  msrv:
    description: Minimum supported Rust version
    value: ${{ steps.msrv.outputs.msrv }}

runs:
  using: composite
  steps:
    - name: Read MSRV from Cargo.toml
      id: msrv
      shell: bash
      run: |
        set -euo pipefail
        if ! command -v jq >/dev/null 2>&1; then
          sudo apt-get update -y && sudo apt-get install -y jq
        fi
        RV=$(cargo metadata --no-deps --format-version=1 | jq -r '.packages[0].rust_version // empty')
        if [ -z "$RV" ]; then
          echo "rust-version is not set in Cargo.toml"
          exit 1
        fi
        [[ "$RV" =~ ^[0-9]+\.[0-9]+$ ]] && RV="${RV}.0"
        echo "msrv=${RV}" >> "$GITHUB_OUTPUT"
        echo "Using MSRV: $RV"
